### PR TITLE
Add SPlus Code Snipper Event And Callback Function 

### PR DESCRIPTION
**Pull request by zhouji0212**
Can U Fix Hilight About Event Key？

### CODE REVIEW

**Comment by sentry07** [comment]
I can definitely merge in the changes you've added to snippets. I'm not understanding what you want me to fix though.

**Comment by zhouji0212** [comment]
i want hi-light the key word of eventhandler. now i can't pack this extension.when i pack it show can't find enterpoint. can u fix this?

**Comment by sentry07** [comment]
Ok. I've added eventhandler to the syntax highlighting and I've updated the entrypoint on the extension. Version 0.5.2 is publishing to the marketplace. Please update and try it.

**Comment by zhouji0212** [comment]
thanks！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月1日(星期二) 凌晨4:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sentry07/vscode-crestron-splus] Add SPlus Code Snipper Event And Callback Function  (PR #21)





 
Ok. I've added eventhandler to the syntax highlighting and I've updated the entrypoint on the extension. Version 0.5.2 is publishing to the marketplace. Please update and try it.
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
